output:
  type: com.amadeus.dataio.pipes.elk.streaming.ElkOutput
  fields:
    - name: Trigger
      mandatory: "No"
      description: Sets the trigger for the stream query. Can be AvailableNow, Continuous or empty. Controls the trigger() Spark function.
      example: Trigger = "AvailableNow"
    - name: Duration
      mandatory: "No"
      description: Sets the trigger for the stream query. Controls the trigger() Spark function. In case no Trigger is defined, will set a ProcessingTime trigger.
      example: Duration = "60 seconds"
    - name: Timeout
      mandatory: "Yes"
      description: Controls the amount of time before returning from the streaming query, in hours. It can be a String or an Int.
      example: Timeout = 24
    - name: Mode
      mandatory: "Yes"
      description: The Spark Structured Streaming output mode.
      example: Mode = "complete"
      default: append