output:
  type: com.amadeus.dataio.pipes.snowflake.streaming.SnowflakeOutput
  fields:
  - name: Duration
    mandatory: "No"
    description: Sets the trigger for the stream query. Controls the trigger() Spark function.
    example: Duration = "60 seconds"
  - name: Timeout
    mandatory: "Yes"
    description: Controls the amount of time before returning from the streaming query, in hours. It can be a String or an Int.
    example: Timeout = 24
  - name: Mode
    mandatory: "Yes"
    description: The Spark Structured Streaming output mode.
    example: Mode = "complete"
    default: append
  - name: AddTimestampOnInsert
    mandatory: "No"
    description: Add a column named "timestamp" containing the current timestamp at the start of query evaluation
    example: AddTimestampOnInsert = "true"
    default: false
