name: Email
description: Allows to send files by email.

code_directory: email

links:
  - name: javax.mail JavaDoc
    url: https://docs.oracle.com/javaee/7/api/javax/mail/package-summary.html

fields:
- name: SmtpHost
  mandatory: "Yes"
  description: The SMTP host to use to send emails.
- name: SmtpUser
  mandatory: "Yes"
  description: The SMTP username to use to authenticate.
- name: SmtpPassword
  mandatory: "Yes"
  description: The SMTP password to use to authenticate.
- name: From
  mandatory: "Yes"
  description: Specifies the sender's email address.
  example: "me@mycompany.com"
- name: To
  mandatory: "Yes"
  description: Specifies the recipient's email address.
  example: "[\"john@smith.com\"]"
- name: Cc
  description: Allows you to include additional recipients in the "Cc" (carbon copy) field of the email.
  example: "[\"john@smith.com\"]"
- name: Bcc
  description: Enables the inclusion of recipients in the "Bcc" (blind carbon copy) field of the email.
  example: "[\"john@smith.com\"]"
- name: Subject
  mandatory: "Yes"
  description: Sets the subject line of the email.
- name: Body
  description: Provides the body content of the email.
- name: Compressed
  description: A boolean flag indicating whether the email attachments are compressed.
  example: true
  default: false

