name: Kafka
description: Allows the connection to Kafka brokers to automatically consume or publish data to a topic in streaming.

code_directory: kafka

links:
  - name: Spark Kafka integration guide
    url: https://spark.apache.org/docs/3.2.1/structured-streaming-kafka-integration.html

top_warning: Please note that Kafka pipes return (read) or accept (write) dataframes with Kafka schema.

fields:
  - name: options
    description: Spark options, as key = value pairs. Note that you need to provide Kafka options as you would in any Spark Kafka application.
    example: options { "kafka.bootstrap.servers" = "kafka.bootstrap.mycompany.net:443" }
