input:
  type: com.amadeus.dataio.pipes.kafka.streaming.KafkaInput
  fields:
    - name: repartition
      description: Matches the Spark Dataset repartition function, either by number, expressions or both.
      example: repartition { num = 10, exprs = "upd_date" }
    - name: coalesce
      description: Matches the Spark Dataset coalesce function.
      example: coalesce = 10
    - name: schema
      description: The schema of the input dataset. See <a href="/configuration/pipes/pipes.html#schema-definitions">schema definitions</a> for more information.
      example: schema = "myproject.models.Query"

output:
  type: com.amadeus.dataio.pipes.kafka.streaming.KafkaOutput
  fields:
    - name: trigger
      mandatory: "No"
      description: Sets the trigger for the stream query. Can be AvailableNow, Continuous or empty. Controls the trigger() Spark function.
      example: trigger = "AvailableNow"
    - name: duration
      mandatory: "No"
      description: Sets the trigger for the stream query. Controls the trigger() Spark function. In case no trigger is defined, will set a ProcessingTime trigger.
      example: duration = "60 seconds"
    - name: timeout
      mandatory: "Yes"
      description: Controls the amount of time before returning from the streaming query, in hours. It can be a String or an Int.
      example: timeout = 24
    - name: mode
      mandatory: "Yes"
      description: The Spark Structured Streaming output mode.
      example: mode = "complete"
      default: append
