name: "CI"

on:
  push:
    branches: [ "main" ]
    paths-ignore: ["docs/**", "**/*.md", "**/LICENSE", "**/.gitignore"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["docs/**", "**/*.md", "**/LICENSE", "**/.gitignore"]
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 8
          cache: "sbt"

      - run: sbt compile

      - run: sbt test

      - run: sbt package

      - run: tar cf artefacts.tar target/ */target/

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: Artefacts
          path: artefacts.tar

