name: Publish

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: The type of release to publish. See SemVer 2.0.0.
        options:
          - PATCH
          - MINOR
          - MAJOR

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_REGISTRY_TOKEN: ${{ secrets.TOKEN }}
      RELEASE_TYPE: ${{ inputs.release_type }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: "temurin"
          cache: "sbt"

      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.10.11

      - name: Run SBT release
        run: sbt release with-defaults

run-name: ${{ format('Publishing new version - {0}', inputs.release_type) }}