name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (SemVer)'
        type: string
        required: true
      spark-version:
        description: 'Spark version override (SemVer)'
        type: string
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION: ${{ inputs.version }}
      GITHUB_REGISTRY_TOKEN: ${{ secrets.TOKEN }}
    steps: 
    - uses: actions/checkout@v4
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: "temurin"
        cache: "sbt"
    - if: ${{ github.event.inputs.spark-version != '' }}
      env:
        SPARK_VERSION: ${{ inputs.spark-version }}
      run: echo "SPARK_VERSION_OVERRIDE=${SPARK_VERSION}" >> $GITHUB_ENV
    - run: sbt "release release-version ${VERSION} with-defaults"

run-name: ${{ github.event.inputs.spark-version != '' 
    && format('Publishing version {0} with Spark {1}', inputs.version, inputs.spark-version) 
    || format('Publishing version {0}', inputs.version)
  }}
