name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (SemVer)'
        type: string
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION: ${{ inputs.version }}
      GITHUB_REGISTRY_TOKEN: ${{ secrets.TOKEN }}
    steps: 
    - uses: actions/checkout@v4
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: "temurin"
        cache: "sbt"
    - run: sbt "release release-version ${VERSION} with-defaults"

run-name: ${{ format('Publishing version {0}', inputs.version) }}
